import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./Component/Header/Header";
import Footer from "./Component/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Header />
        <main className="transition duration-700 ease-linear dark:bg-neutral-900 dark:text-white">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
